[2023-09-20T12:41:32.241+0530] {processor.py:157} INFO - Started process (PID=13295) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:41:32.243+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:41:32.247+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.247+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:41:32.563+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.562+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:41:32.568+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:41:32.710+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.709+0530] {manager.py:499} INFO - Created Permission View: %s
[2023-09-20T12:41:32.725+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.725+0530] {manager.py:499} INFO - Created Permission View: %s
[2023-09-20T12:41:32.736+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.736+0530] {manager.py:499} INFO - Created Permission View: %s
[2023-09-20T12:41:32.736+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.736+0530] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:spacex_rockets_pipeline' as access control is unset.
[2023-09-20T12:41:32.737+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.736+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:41:32.754+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.754+0530] {dag.py:2937} INFO - Creating ORM DAG for spacex_rockets_pipeline
[2023-09-20T12:41:32.767+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:41:32.766+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:41:32.795+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.559 seconds
[2023-09-20T12:42:03.218+0530] {processor.py:157} INFO - Started process (PID=13316) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:42:03.219+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:42:03.224+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:03.224+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:42:03.332+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:03.331+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:42:03.337+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:42:03.369+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:03.368+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:42:03.399+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:03.399+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:42:03.434+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.222 seconds
[2023-09-20T12:42:33.730+0530] {processor.py:157} INFO - Started process (PID=13474) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:42:33.736+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:42:33.740+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:33.740+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:42:33.856+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:33.855+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:42:33.862+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:42:33.905+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:33.904+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:42:33.947+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:42:33.947+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:42:33.988+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.264 seconds
[2023-09-20T12:43:04.220+0530] {processor.py:157} INFO - Started process (PID=13583) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:43:04.222+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:43:04.226+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:04.225+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:43:04.322+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:04.320+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:43:04.327+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:43:04.358+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:04.357+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:43:04.390+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:04.390+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:43:04.419+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.204 seconds
[2023-09-20T12:43:34.695+0530] {processor.py:157} INFO - Started process (PID=13612) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:43:34.697+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:43:34.702+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:34.702+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:43:34.812+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:34.809+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:43:34.821+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:43:34.856+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:34.855+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:43:34.887+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:43:34.887+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:43:34.918+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.229 seconds
[2023-09-20T12:44:05.080+0530] {processor.py:157} INFO - Started process (PID=13644) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:44:05.081+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:44:05.086+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:05.085+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:44:05.188+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:05.187+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:44:05.194+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:44:05.224+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:05.223+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:44:05.257+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:05.256+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:44:05.285+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.211 seconds
[2023-09-20T12:44:35.480+0530] {processor.py:157} INFO - Started process (PID=13676) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:44:35.482+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:44:35.486+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:35.486+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:44:35.584+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:35.583+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:44:35.589+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:44:35.621+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:35.621+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:44:35.652+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:44:35.651+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:44:35.682+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.207 seconds
[2023-09-20T12:45:05.983+0530] {processor.py:157} INFO - Started process (PID=13714) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:45:05.984+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:45:05.988+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:05.988+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:45:06.083+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:06.082+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:45:06.088+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:45:06.118+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:06.118+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:45:06.148+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:06.148+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:45:06.178+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.201 seconds
[2023-09-20T12:45:36.443+0530] {processor.py:157} INFO - Started process (PID=13754) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:45:36.445+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:45:36.450+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:36.449+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:45:36.547+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:36.546+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:45:36.553+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:45:36.583+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:36.583+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:45:36.615+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:45:36.615+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:45:36.644+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.207 seconds
[2023-09-20T12:46:06.859+0530] {processor.py:157} INFO - Started process (PID=13789) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:46:06.861+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:46:06.865+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:06.864+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:46:06.961+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:06.959+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:46:06.967+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:46:06.997+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:06.996+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:46:07.027+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:07.027+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:46:07.056+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.203 seconds
[2023-09-20T12:46:37.185+0530] {processor.py:157} INFO - Started process (PID=13829) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:46:37.187+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:46:37.191+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:37.190+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:46:37.287+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:37.286+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:46:37.292+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:46:37.322+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:37.321+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:46:37.354+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:46:37.353+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:46:37.382+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.201 seconds
[2023-09-20T12:47:07.846+0530] {processor.py:157} INFO - Started process (PID=13853) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:47:07.850+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:47:07.864+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:07.863+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:47:08.027+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:08.024+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:47:08.034+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:47:08.093+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:08.091+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:47:08.138+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:08.137+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:47:08.184+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.347 seconds
[2023-09-20T12:47:38.336+0530] {processor.py:157} INFO - Started process (PID=13893) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:47:38.338+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:47:38.342+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:38.342+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:47:38.442+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:38.441+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:47:38.448+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:47:38.477+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:38.477+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:47:38.507+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:47:38.507+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:47:38.536+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.206 seconds
[2023-09-20T12:48:08.795+0530] {processor.py:157} INFO - Started process (PID=13926) to work on /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:48:08.798+0530] {processor.py:829} INFO - Processing file /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py for tasks to queue
[2023-09-20T12:48:08.804+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:08.804+0530] {dagbag.py:539} INFO - Filling up the DagBag from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:48:08.980+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:08.978+0530] {templater.py:78} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/airflow/template/templater.py", line 76, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/osairis/SpaceX-Data-Engineering-Project/myvenv/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/copy_rockets.sql
[2023-09-20T12:48:08.994+0530] {processor.py:839} INFO - DAG(s) dict_keys(['spacex_rockets_pipeline']) retrieved from /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py
[2023-09-20T12:48:09.053+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:09.052+0530] {dag.py:2915} INFO - Sync 1 DAGs
[2023-09-20T12:48:09.123+0530] {logging_mixin.py:151} INFO - [2023-09-20T12:48:09.122+0530] {dag.py:3696} INFO - Setting next_dagrun for spacex_rockets_pipeline to 2023-09-06T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-20T12:48:09.158+0530] {processor.py:179} INFO - Processing /home/osairis/SpaceX-Data-Engineering-Project/airflow/dags/spacex_rockets.py took 0.369 seconds
